<a href="https://colab.research.google.com/github/anuvishalp/Python_DataCleaning-Basics/blob/master/London_housingDataAnalysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install pandas
import pandas as pd

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
from google.colab import files
uploaded=files.upload()

Saving LondonHousingData.csv to LondonHousingData.csv

In [3]:
import pandas as pd
ld=pd.read_csv('LondonHousingData.csv')

In [4]:
ld.shape

(13549, 6)

In [5]:
ld.count

<bound method DataFrame.count of             date            area  average_price       code  houses_sold  \
0       1/1/1995  city of london          91449  E09000001         17.0
1       2/1/1995  city of london          82203  E09000001          7.0
2       3/1/1995  city of london          79121  E09000001         14.0
3       4/1/1995  city of london          77101  E09000001          7.0
4       5/1/1995  city of london          84409  E09000001         10.0
...          ...             ...            ...        ...          ...
13544   9/1/2019         england         249942  E92000001      64605.0
13545  10/1/2019         england         249376  E92000001      68677.0
13546  11/1/2019         england         248515  E92000001      67814.0
13547  12/1/2019         england         250410  E92000001          NaN
13548   1/1/2020         england         247355  E92000001          NaN

       no_of_crimes
0               NaN
1               NaN
2               NaN
3               NaN
4               NaN
...             ...
13544           NaN
13545           NaN
13546           NaN
13547           NaN
13548           NaN

[13549 rows x 6 columns]>

In [6]:
ld.count()

date             13549
area             13549
average_price    13549
code             13549
houses_sold      13455
no_of_crimes      7439
dtype: int64

In [7]:
ld.isnull()

        date   area  average_price   code  houses_sold  no_of_crimes
0      False  False          False  False        False          True
1      False  False          False  False        False          True
2      False  False          False  False        False          True
3      False  False          False  False        False          True
4      False  False          False  False        False          True
...      ...    ...            ...    ...          ...           ...
13544  False  False          False  False        False          True
13545  False  False          False  False        False          True
13546  False  False          False  False        False          True
13547  False  False          False  False         True          True
13548  False  False          False  False         True          True

[13549 rows x 6 columns]

In [8]:
ld.isnull().sum()

date                0
area                0
average_price       0
code                0
houses_sold        94
no_of_crimes     6110
dtype: int64

In [9]:
ld.dtypes

date              object
area              object
average_price      int64
code              object
houses_sold      float64
no_of_crimes     float64
dtype: object

In [10]:
ld.date=pd.to_datetime(ld.date)

In [11]:
ld.head(2)

,date,area,average_price,code,houses_sold,no_of_crimes
0,1995-01-01,city of london,91449,E09000001,17.0,NaN
1,1995-02-01,city of london,82203,E09000001,7.0,NaN

In [12]:
ld.head(3)

,date,area,average_price,code,houses_sold,no_of_crimes
0,1995-01-01,city of london,91449,E09000001,17.0,NaN
1,1995-02-01,city of london,82203,E09000001,7.0,NaN
2,1995-03-01,city of london,79121,E09000001,14.0,NaN

In [13]:
ld['year']= ld.date.dt.year

In [14]:
ld.insert(1,'months',ld.date.dt.month)

In [15]:
ld

,date,months,area,average_price,code,houses_sold,no_of_crimes,year
0,1995-01-01,1,city of london,91449,E09000001,17.0,NaN,1995
1,1995-02-01,2,city of london,82203,E09000001,7.0,NaN,1995
2,1995-03-01,3,city of london,79121,E09000001,14.0,NaN,1995
3,1995-04-01,4,city of london,77101,E09000001,7.0,NaN,1995
4,1995-05-01,5,city of london,84409,E09000001,10.0,NaN,1995
...,...,...,...,...,...,...,...,...
13544,2019-09-01,9,england,249942,E92000001,64605.0,NaN,2019
13545,2019-10-01,10,england,249376,E92000001,68677.0,NaN,2019
13546,2019-11-01,11,england,248515,E92000001,67814.0,NaN,2019
13547,2019-12-01,12,england,250410,E92000001,NaN,NaN,2019
13548,2020-01-01,1,england,247355,E92000001,NaN,NaN,2020

In [22]:
ld.drop(['year','months'], axis=1,inplace=True)

In [23]:
ld

,date,area,average_price,code,houses_sold,no_of_crimes
0,1995-01-01,city of london,91449,E09000001,17.0,NaN
1,1995-02-01,city of london,82203,E09000001,7.0,NaN
2,1995-03-01,city of london,79121,E09000001,14.0,NaN
3,1995-04-01,city of london,77101,E09000001,7.0,NaN
4,1995-05-01,city of london,84409,E09000001,10.0,NaN
...,...,...,...,...,...,...
13544,2019-09-01,england,249942,E92000001,64605.0,NaN
13545,2019-10-01,england,249376,E92000001,68677.0,NaN
13546,2019-11-01,england,248515,E92000001,67814.0,NaN
13547,2019-12-01,england,250410,E92000001,NaN,NaN
13548,2020-01-01,england,247355,E92000001,NaN,NaN

In [24]:
ld.no_of_crimes==0

0        False
1        False
2        False
3        False
4        False
         ...
13544    False
13545    False
13546    False
13547    False
13548    False
Name: no_of_crimes, Length: 13549, dtype: bool

In [25]:
ld[ld.no_of_crimes==0]

,date,area,average_price,code,houses_sold,no_of_crimes
72,2001-01-01,city of london,284262,E09000001,24.0,0.0
73,2001-02-01,city of london,198137,E09000001,37.0,0.0
74,2001-03-01,city of london,189033,E09000001,44.0,0.0
75,2001-04-01,city of london,205494,E09000001,38.0,0.0
76,2001-05-01,city of london,223459,E09000001,30.0,0.0
...,...,...,...,...,...,...
178,2009-11-01,city of london,397909,E09000001,11.0,0.0
179,2009-12-01,city of london,411955,E09000001,16.0,0.0
180,2010-01-01,city of london,464436,E09000001,20.0,0.0
181,2010-02-01,city of london,490525,E09000001,9.0,0.0
182,2010-03-01,city of london,498241,E09000001,15.0,0.0

In [26]:
len(ld[ld.no_of_crimes==0])

104

In [27]:
ld[ld.area == 'houses']

Empty DataFrame
Columns: [date, area, average_price, code, houses_sold, no_of_crimes]
Index: []

In [28]:
ld.groupby('area').no_of_crimes.max()

area
barking and dagenham      2049.0
barnet                    2893.0
bexley                    1914.0
brent                     2937.0
bromley                   2637.0
camden                    4558.0
city of london              10.0
croydon                   3263.0
ealing                    3401.0
east midlands                NaN
east of england              NaN
enfield                   2798.0
england                      NaN
greenwich                 2853.0
hackney                   3466.0
hammersmith and fulham    2645.0
haringey                  3199.0
harrow                    1763.0
havering                  1956.0
hillingdon                2819.0
hounslow                  2817.0
inner london                 NaN
islington                 3384.0
kensington and chelsea    2778.0
kingston upon thames      1379.0
lambeth                   4701.0
lewisham                  2813.0
london                       NaN
merton                    1623.0
newham                    3668.0
north east                   NaN
north west                   NaN
outer london                 NaN
redbridge                 2560.0
richmond upon thames      1551.0
south east                   NaN
south west                   NaN
southwark                 3821.0
sutton                    1425.0
tower hamlets             3316.0
waltham forest            2941.0
wandsworth                3051.0
west midlands                NaN
westminster               7461.0
yorks and the humber         NaN
Name: no_of_crimes, dtype: float64

In [30]:
#ld.groupby('year').average_price.max()

KeyError: 'year'

In [31]:
ld.groupby('area').average_price.sort_values(ascending=True)

AttributeError: 'SeriesGroupBy' object has no attribute 'sort_values'

In [32]:
ld.groupby('area').no_of_crimes.min().sort_values(ascending=True)

area
city of london               0.0
kingston upon thames       692.0
richmond upon thames       700.0
sutton                     787.0
merton                     819.0
bexley                     860.0
harrow                     937.0
havering                  1130.0
barking and dagenham      1217.0
hammersmith and fulham    1323.0
kensington and chelsea    1347.0
bromley                   1441.0
hillingdon                1445.0
redbridge                 1487.0
greenwich                 1513.0
hounslow                  1529.0
haringey                  1536.0
waltham forest            1575.0
wandsworth                1582.0
enfield                   1635.0
tower hamlets             1646.0
lewisham                  1675.0
barnet                    1703.0
brent                     1850.0
hackney                   1870.0
islington                 1871.0
ealing                    1871.0
croydon                   2031.0
camden                    2079.0
newham                    2130.0
southwark                 2267.0
lambeth                   2381.0
westminster               3504.0
east midlands                NaN
east of england              NaN
england                      NaN
inner london                 NaN
london                       NaN
north east                   NaN
north west                   NaN
outer london                 NaN
south east                   NaN
south west                   NaN
west midlands                NaN
yorks and the humber         NaN
Name: no_of_crimes, dtype: float64

In [33]:
ld.average_price<100000

0         True
1         True
2         True
3         True
4         True
         ...
13544    False
13545    False
13546    False
13547    False
13548    False
Name: average_price, Length: 13549, dtype: bool

In [34]:
ld[ld.average_price < 100000]

,date,area,average_price,code,houses_sold,no_of_crimes
0,1995-01-01,city of london,91449,E09000001,17.0,NaN
1,1995-02-01,city of london,82203,E09000001,7.0,NaN
2,1995-03-01,city of london,79121,E09000001,14.0,NaN
3,1995-04-01,city of london,77101,E09000001,7.0,NaN
4,1995-05-01,city of london,84409,E09000001,10.0,NaN
...,...,...,...,...,...,...
13330,2001-11-01,england,95083,E92000001,109149.0,NaN
13331,2001-12-01,england,95992,E92000001,93329.0,NaN
13332,2002-01-01,england,96215,E92000001,71678.0,NaN
13333,2002-02-01,england,96676,E92000001,77131.0,NaN
13334,2002-03-01,england,98962,E92000001,102828.0,NaN

In [35]:
ld[ld.average_price < 100000].area

0        city of london
1        city of london
2        city of london
3        city of london
4        city of london
              ...
13330           england
13331           england
13332           england
13333           england
13334           england
Name: area, Length: 2209, dtype: object

In [36]:
ld[ld.average_price < 100000].area.value_counts()

area
north east              112
north west              111
yorks and the humber    110
east midlands            96
west midlands            94
england                  87
barking and dagenham     85
south west               78
east of england          76
newham                   72
bexley                   64
waltham forest           64
lewisham                 62
havering                 60
south east               59
greenwich                59
croydon                  57
sutton                   54
enfield                  54
hackney                  53
redbridge                52
southwark                48
tower hamlets            47
outer london             46
hillingdon               44
hounslow                 41
lambeth                  41
brent                    40
london                   39
merton                   35
haringey                 33
bromley                  33
ealing                   31
inner london             31
harrow                   30
kingston upon thames     30
wandsworth               26
barnet                   25
islington                19
city of london           11
Name: count, dtype: int64